diseaseMatcher/urls.py
from django.conf.urls import patterns, include, url
from diseaseMatcherApp import views
from diseaseMatcher import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

    url(r'^admin/', include(admin.site.urls)),
    url(r'^diseaseMatcher/', include('diseaseMatcherApp.urls', namespace='diseaseMatcherApp')),
    url(r'^$', views.home_page, name='homePage'),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'diseaseMatcherApp/login.html'}, name='login'),
    url(r'^accounts/registration/$', views.start_registration, name='registration'),
    url(r'^accounts/processRegistration/$', views.process_registration, name='process_registration'),
    url(r'^accounts/logout/$', views.logout_view, name='logout')

)

'''Adding this to help heroku serve up my static files with gunicorn.  Not 100% clear if this is necessary.
    Also, this gives a "Could not import django.contrib.staticfiles.views. View is not callable."

urlpatterns += patterns('',
        (r'^static/(?P<path>.*)$', 'django.contrib.staticfiles.views', {'document_root': settings.STATIC_ROOT}),
    )
'''

diseaseMatcherApp/urls.py
__author__ = 'Doug'

from django.conf.urls import url, patterns
from diseaseMatcherApp import views

urlpatterns = patterns('',
url(r'^$', views.home_page, name='homePage'),
url(r'^(?P<pk>\d+)/detail/$', views.AbstractDetailView.as_view(), name='abstractDetail'),
url(r'^process_matches/$', views.process_matches, name='processMatches'),
url(r'^play_again/$', views.play_again, name='playAgain'),
url(r'^user_profile/$', views.user_profile, name='userProfile')


)

diseaseMatcherApp/views.py
from __future__ import absolute_import
import json

#TODO: Replace get() calls with get_object_or_404
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.template import loader, context, RequestContext
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .models import Matches, Abstract, MatchLocations, Annotator, GoldStandardMatch

'''Principles of Views

--Less view code is better
--Never repeat code in views
--Views should handle presentation logic.  Try to keep business login in models (or forms if necessary).
--Keep views simple
--Use function-based views to write custom 403,404, and 500 handlers.
--Avoid complex nested-if blocks
--Keep mixins simpler (Mixin = abstract class.  When inheriting, always put mixin as left argument, django class as right argument.  All mixins inherit from 'object').
'''

#TODO: Can I set a global variable for DeepMatcher vs. Speedmatcher, and then modularize base.py?
#       Will probably still need to keep abstractDetail and process_matches separate.

# **********VIEWS**********
@login_required
def home_page(request):
    #create a welcome page
    template = loader.get_template('diseaseMatcherApp/index.html')

    user = Annotator.objects.get(pk=request.user.id)

    #pick a random abstract that this user hasn't seen before
    rnd = user.get_a_fresh_abstract()
    context = RequestContext(request, {'abstract_choice': rnd, 'user': user})

    return HttpResponse(template.render(context))


def start_registration(request):

    template = loader.get_template('diseaseMatcherApp/register.html')
    context = RequestContext(request)

    return HttpResponse(template.render(context))


class AbstractDetailView(generic.DetailView):
    #What the user will see while they search for disease names
    template_name = 'diseaseMatcherApp/abstractDetail.html'
    context_object_name = 'abstract'
    model = Abstract

    def a_function(self):
        return 99


@login_required
def logout_view(request):
    logout(request)

    return HttpResponseRedirect(reverse('login'))


@login_required
def play_again(request):
    template = loader.get_template('diseaseMatcherApp/playAgain.html')

    #TODO: Should this page be a modular version of the home page?
    #Maybe this becomes a post-login and post-game "get started" page that also shows recent activity,
    #   fulfilling the role of visually rewarding the player for completion
    user = Annotator.objects.get(pk=request.user.id)
    rnd = user.get_a_fresh_abstract()

    context = RequestContext(request,{'abstract_choice': rnd, 'user': user})

    return HttpResponse(template.render(context))


@login_required
def user_profile(request):
    template = loader.get_template('diseaseMatcherApp/userProfile.html')
    #get count of matches found, and in how many abstracts.  Maybe grid of title + matches?
    #user ranking (based on # matches, get all users with more matches, ranking = that + 1

    dict_of_work = {}

    this_user = Annotator.objects.get(pk=request.user.id)
    abstracts_worked_on = Matches.objects.filter(annotator_id=this_user.pk).values_list('abstract_id', flat=True).distinct()

    work_count = abstracts_worked_on.count

    my_rank = this_user.calculate_ranking()

    for abstract in abstracts_worked_on:
        match_name = Abstract.objects.get(pk=abstract).title
        match_count = Matches.objects.filter(abstract_id=abstract).count()
        dict_of_work[match_name] = match_count

    #TODO: Neither of these sorts is producing a working dictionary.  Maybe because it's a list of tuples?
    #sorted_dict_of_work = sorted(dict_of_work.items(), key=lambda x: x[1])
    #sorted_dict_of_work = sorted(dict_of_work.iteritems(), key=operator.itemgetter(1))


    context = RequestContext(request, {'abstractsWorkedOn': dict_of_work, 'abstractCount': work_count, 'rank': my_rank})

    return HttpResponse(template.render(context))


#*********TRANSACTIONS************

def process_registration(request):
    #See if registration already exists.  If yes + correct PW, login + index.html.  If yes + wrong PW, back to register
    username = request.POST['username']
    password = request.POST['password']

    user = authenticate(username=username, password=password)

    if user is not None:
        if user.is_active:
            login(request, user)
            return HttpResponseRedirect(reverse('homePage'))
        else:
            messages.success(request, "you're a user, but you have been disabled.")
            return HttpResponseRedirect(reverse('registration'))
    else:
        #If username isn't taken, create user and login
        try:
            new_user = User.objects.create_user(username=username, password=password)
            new_user.save()

        except:  #TODO: specify exception classes
            messages.error(request, "Failed on create new user.  Username is probably taken, try another.")
            return HttpResponseRedirect(reverse('registration'))

        try:
            #Now that the user has been created, we can authenticate with the user/pass we used to create them
            user_trying_again = authenticate(username=username, password=password)
            login(request, user_trying_again)
        except:
            messages.error(request, "Login failed after (possibly) creating user " + str(new_user))

        return HttpResponseRedirect(reverse('homePage'))


@login_required
def process_matches(request):
    #TODO: refactor the heck out of this monstrosity
    #TODO: Build better test for process_matches

    '''
    This is the action on the abstractDetail.html form post.  It takes game answers and puts them in the database.
    Text-entered answers and mouse-selected answers are handled differently, because they are many-to-one and one-to-one respectively.


    :param request:
    :return:
    '''

    #List of all words entered, in a space-delimited string
    try:
        which_abstract = request.POST.get('abstract_pk')
        answer_time_dict = json.loads(request.POST.get('userTypedMatches'))
        selected_text_time_dict = json.loads(request.POST.get('userHighlightedMatches'))
    except:
        raise Exception('Problem with post data.  abstract_pk = ' + str(request.POST.get("abstract_pk")) + ', userTypedMatches = ' +
                        str(request.POST.get("userTypedMatches")) + ', userHighlightedMatches = ' + str(request.POST.get("userHighlightedMatches")))

    annotator_pk = Annotator.objects.get(pk=request.user.id)
    abstract_pk = Abstract.objects.get(pk=which_abstract)
    answers = []

    for key in answer_time_dict:
        answers.append(key)

    for key in selected_text_time_dict:
        answers.append(key)

    for answer in answers:
        clean_answer = answer.strip()

    ###  Begin processing text-entered answer here
        if 51 > len(clean_answer) > 0:
            if clean_answer in answer_time_dict:#TODO: This will cause a silent error when both ifs false (happens when user submits, then hits back button.  Prevent this?)

                this_match_time = answer_time_dict[clean_answer]["secondsInt"]
                temp_int_holder = answer_time_dict[clean_answer]["goldStandard"]  #TODO: find the actual GS with location/offset match instead of just first.  Do this inside offset_list loop.  Change models to move gold_standard_match to MatchLocations (not Matches)

                '''
                WORKPLAN: see "The Gold Standard Problem" in Models before starting
                1) test_for_gold_standard_typed_text_match grabs first GS match, could easily grab all
                2) Get all GS where text and abstract ID match; pull all location data
                3) Create MatchLocations based on this.  WAIT - are we not already recording these, because they're also text matches?  Find the IF that turns that off.

                '''


                if temp_int_holder == 0:
                    gsmatch = None
                else:
                    gsmatch = GoldStandardMatch.objects.get(pk=temp_int_holder)

                #This function of the Abstract object returns all match locations based on string matching
                offset_list = abstract_pk.match_location(clean_answer)

                if offset_list[0][0] != -1:
                    try:
                        #create Match record here.  Fields: abstract, annotator, text_matches, match_length, match_time
                        match = Matches.objects.create(abstract=abstract_pk, annotator=annotator_pk, text_matched=clean_answer,
                                                       match_length=len(clean_answer), match_time=this_match_time,
                                                       gold_standard_match=gsmatch)

                        match.save()

                        for offset in offset_list:
                            #format of offset variable will be [HowDeepInTextAppears, MatchLocationAs0or1].  No match = [-1,-1]
                            if offset[0] != -1:
                                this_match_location = offset[1]

                                #Create MatchLocations here.  Fields: match, match_location, match_offset

                                where_we_matched = MatchLocations.objects.create(match=match, match_location=this_match_location,
                                                                                 match_offset=offset[0])

                                where_we_matched.save()
                    except:
                        raise Exception("Something went screwy creating text-entered match records in the database.  " + str(offset_list[0][0]))

            ### Begin processing mouse-selected answers here

diseaseMatcherApp/templates/diseaseMatcherApp/abstractDetail.html
{% extends 'diseaseMatcherApp/base.html' %}

{% block title %}
    {{ abstract.title }}
{% endblock %}

{% block extrascripts %}
    {% load sstatic %}
    <script>
        data_for_js = JSON.parse('{{ abstract.gold_standard_match | safe }}');
    </script>

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="{% sstatic 'diseaseMatcherApp/UI-helper-abstractDetail.js' %}"></script>
{% endblock %}

{% block content %}
    <span class="instructions">Highlight disease names with your mouse, or type them in the box below and press Enter.</span>

    <div id="abstractTitleDiv">
        <h1>{{ abstract.title }}</h1>
    </div>
    <div id="abstractTextDiv">
        {{ abstract.abstract_text }}
    </div>

    <hr>
    <form action="{% url 'diseaseMatcherApp:processMatches' %}" method="post" id="detailForm" autocomplete="off">
    {% csrf_token %}

        <div id="leftColumn">
            <div id="topChunk">
                <label for="userInput" id="textEntryColumnAnchor">Type disease names here:</label>
                <br>
                <input type="text" id="userInput" name="userInput" autocomplete="off"><br>
                <span id="feedback" style="font-style:italic">(press ENTER to submit each answer)</span>
            </div>
            <div id="bottomChunk">
                <label for="submitButton" id="secondsLeft"></label> seconds left.
                <p><input id="submitButton" type="submit" value="Done"></p>
            </div>
        </div>
        <div id="rightColumn">
            <label for="anwerDisplay">You have entered:</label><br>
            <table id="answerDisplay">
                <thead>
                    <tr>
                        <th>
                            Answer
                        </th>
                        <th>
                            Delete?
                        </th>
                    </tr>
                </thead>
                <tbody id="answerBody" class="answerTable">

                </tbody>

            </table>
            <span id="goldStandardFeedback" style="font-style:italic"></span>
        </div>



        <input type="hidden" id="abstract_pk" name="abstract_pk" value="{{ abstract.id }}">
        <input type="hidden" id="userTypedMatches" name="userTypedMatches" value="">
        <input type="hidden" id="userHighlightedMatches" name="userHighlightedMatches" value="">

    </form>
{% endblock %}

diseaseMatcherApp/templates/diseaseMatcherApp/abstractList.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'diseaseMatcherApp/styles.css' %}"
</head>
<body>

{% for abstract in abstract_list %}
    TITLE: {{ abstract.title }}<br>
    <textarea>{{ abstract.abstract_text }}</textarea><br>
{% endfor %}


</body>
</html>

diseaseMatcherApp/templates/diseaseMatcherApp/base.html
{% load sstatic %}

<!DOCTYPE html>
<html>
<!-- TODO: Incorporate ranking into base.html.-->
<head lang="en">
    <meta charset="UTF-8">
    <title>{% block title %}Disease Matcher{% endblock %}</title>
    <meta name="description" content="{% block metadescription%}Disease Matcher is a free game that lets you have fun while contributing to science.{% endblock %}">
    <meta name="keywords" content="{% block metakeywords%}citizen science game Disease Matcher{% endblock %}">

    <link rel="stylesheet" type="text/css" href="{% sstatic 'diseaseMatcherApp/styles.css' %}">
    {% block extrascripts %}{% endblock %}<!-- no need to load all scripts to every page -->
</head>
<body>
<img class="ncbi" src="http://upload.wikimedia.org/wikipedia/commons/0/07/US-NLM-NCBI-Logo.svg">
<span class="banner">DISEASE MATCHER</span> <span class="bannerUsername">Welcome, {{ user }}</span><br><br>

<a href="{% url 'diseaseMatcherApp:homePage' %}" class="menuLink">Home</a>
<a href="{% url 'diseaseMatcherApp:userProfile' %}" class="menuLink">See User Profile</a>
<a href="{% url 'logout' %}" class="menuLink">Log Out</a>
<br>
{% block content %}
    Content Goes Here
{% endblock %}

</body>
</html>

diseaseMatcherApp/templates/diseaseMatcherApp/index.html
{%  extends "diseaseMatcherApp/base.html" %}

{% block content %}
<h1>Welcome to Disease Matcher!
    {% if user %}
       Have fun, {{ user }}.
    {% else %}
        Have fun.
    {% endif %}
    </h1>



{% if abstract_choice %}
    <a href="{% url 'diseaseMatcherApp:abstractDetail' abstract_choice%}">Check out this abstract.</a>
{% else %}
    There was no abstract_choice that I could find.
{%  endif %}

{% endblock %}

diseaseMatcherApp/templates/diseaseMatcherApp/login.html
{% extends 'diseaseMatcherApp/base.html' %}
{% block title %}Login{% endblock %}
{% block content %}

<span class="instructions">

{% if form.errors %}

    {%   for field, errors in form.errors.items %}
        {% for error in errors %}
            {{ error }}
        {% endfor %}
    {% endfor %}

{% else %}
    Please log in to play Disease Matcher.  <br>
{% endif %}

Don't have a login?  Then <a href="{% url 'registration' %}">register</a>.
</span>
<form method="post" action="{% url 'django.contrib.auth.views.login' %}">
    {% csrf_token %}

<br>


    <table>
        <tr>
            <td>
                {{ form.username.label_tag }}
            </td>
            <td>
                {{ form.username }}
            </td>
        </tr>
        <tr>
            <td>
                {{ form.password.label_tag }}
            </td>
            <td>
                {{ form.password }}
            </td>
        </tr>
    </table>

    <input type="submit" value="Login">
    <input type="hidden" name="next" value="{{ next }}"
</form>
{% endblock %}

diseaseMatcherApp/templates/diseaseMatcherApp/playAgain.html
{% extends 'diseaseMatcherApp/base.html' %}

{% block content %}
    <h1>You helped science{% if user %}, {{ user }}{% endif %}. Thanks for playing!</h1>

    <a href="{% url 'diseaseMatcherApp:abstractDetail' abstract_choice %}">Play again?</a>

    <a href="{% url 'logout' %}">Log Out</a>
{% endblock %}

diseaseMatcherApp/templates/diseaseMatcherApp/register.html
{% extends 'diseaseMatcherApp/base.html' %}

{% block title %}
    Register
{% endblock %}

{% block content %}

    {% if messages %}
    <ul class="messages">
      {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
    </ul>
    {% endif %}

    <h1>Register for Disease Matcher, and then you can start playing.</h1>

    <!-- TODO: Build this form as a django programmatic form (to easily populate dropdowns).  See Two Scoops.-->

    <form method="post" action="{% url 'process_registration' %}">
        {% csrf_token %}

        <table>
            <tr>
                <td>
                    <label for="username">Username</label>
                </td>
                <td>
                    <input type="text" name="username">
                </td>
            </tr>
            <tr>
                <td>
                    <label for="password">Password</label>
                </td>
                <td>
                    <input type="password" name="password">
                </td>
            </tr>
        </table>

        <input type="submit" value="Register">
    </form>
{% endblock %}

diseaseMatcherApp/templates/diseaseMatcherApp/userProfile.html
{% extends 'diseaseMatcherApp/base.html' %}

{% block title %}
    User Profile
{% endblock %}

{% block content %}

<h1>User profile for {{ user }}</h1><br>

    You are ranked #{{ rank }} in Disease Matcher! <br>

    {% if abstractsWorkedOn %}
        You worked on these {{ abstractCount }} abstracts:
        <table>
        <tr><td>Matches</td><td>Abstract</td></tr>
        {% for key, value in abstractsWorkedOn.items %}
            <tr>
                <td>
                   {{ value }}
                </td>
                <td>
                    {{ key }}
                </td>
            </tr>

        {% endfor %}
        </table>
    {% else %}
        <br>
        You haven't worked on any abstracts yet.  Give one a try!
    {% endif %}


{% endblock %}